#import = ["~/.config/alacritty/catppuccin_frappe.toml"]
import = ["~/.config/alacritty/themes/themes/catppuccin_frappe.toml"]
live_config_reload = true
[bell]
animation = "Linear"
color = "#b59b9c"
duration = 500

[cursor.style]
blinking = "On"
shape = "underline"

[font]
size = 20 

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "ExtraBold"

#[line_indicator]
#background = "#b59b9c"
#foreground = "#b59b9c"

#[mouse.hints]
#modifiers = "Control"

[scrolling]
multiplier = 15

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[window]
#decorations = "transparent"
decorations = "Buttonless"
dynamic_padding = false
dynamic_title = false
opacity = 0.8 
startup_mode = "Windowed"
blur = true 

[window.dimensions]
columns = 150
lines = 45

[window.padding]
x = 0
y = 0

[window.position]
x = 2500
y = 700
